### ISSUE TITLE
Zabbix Server version 4.2.6 data transfer feature

### ISSUE THREAD

**Issue by hotoroy** [vagabondan/node-db4bix#19]
Hi!
I have a problem in Zabbix Server version 4.2.6. - Server don't receive data from querry without any errors. In the process of researching with Vaganbondan we determined that the problem is in the updated exchange format

**Comment by vagabondan** [comment]
Hi!
I've checked it on Zabbix version 4.2.8. Works fine.
Try to check any connection problems to your database from container. Possible reasons are some DNS problems, networks ips intersection (docker networks and your company's networks), iptables restrictions or so on.
Also I advice to get tcpdump from db4bix host to realize what's happenning.
