### ISSUE TITLE
При работе с Postgres происходит зависание открытых сессий БД 

### ISSUE THREAD

**Issue by corish** [vagabondan/node-db4bix#2]
Если запрос в бд возвращает ошибку, то сессия в которой он работал, зависает. Так происходит до окончания пула соединений выделенных для node-db4bix. После окончания пула работа с БД прекращается. В логе наблюдаем сообщение:
timeout exceeded when trying to connect
Запросы:

select round((sum(total_time) / sum(calls))::numeric,2) from pg_stat_statements
select count(*) from pg_buffercache where not isdirty
select count(*) from pg_buffercache where isdirty
select count(*) from pg_buffercache where reldatabase is not null
select count(*) from pg_buffercache
select pg_xlog_location_diff(pg_current_xlog_location(),'0/00000000')
select count(*) from pg_ls_dir('pg_xlog')

**Comment by vagabondan** [comment]
Done with 5ecb779. Please check.

**Comment by corish** [comment]
its work
